---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/projects":
    get:
      summary: Get all projects
      tags:
        - Projects
      security:
        - Bearer: []
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Authorization token
          schema:
            type: string
      responses:
        "200":
          description: projects found
        "401":
          description: unauthorized
    post:
      summary: Create a project
      tags:
        - Projects
      security:
        - Bearer: []
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Authorization token
          schema:
            type: string
      responses:
        "302":
          description: redirected
        "401":
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                project:
                  project_name:
                    type: string
                  project_description:
                    type: string
              required:
                - project_name
                - project_description
          application/xml:
            schema:
              type: object
              properties:
                project:
                  project_name:
                    type: string
                  project_description:
                    type: string
              required:
                - project_name
                - project_description
  "/api/v1/projects/{id}":
    get:
      summary: Get a project
      tags:
        - Projects
      security:
        - Bearer: []
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Authorization token
          schema:
            type: string
        - name: id
          in: path
          required: true
          description: ID of the project
          schema:
            type: string
      responses:
        "200":
          description: project found
        "404":
          description: project not found
        "401":
          description: unauthorized
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: www.example.com
